[package]
name = "edlang"
version = "0.1.0"
authors = ["Edgar Luque <edgar@edgarluque.com>"]
description = "A experimental language using LLVM."
edition = "2021"
readme = "README.md"
keywords = ["llvm", "compiler"]
license = "AGPL-3.0-only"
categories = ["compilers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
color-eyre = "0.6.2"
itertools = "0.10.5"
lalrpop-util = { version = "0.19.9", features = ["lexer"] }
regex = "1.7.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
inkwell = { version = "0.1.1", features = ["llvm15-0"] }
annotate-snippets = { version = "0.9.1", features = ["color"] }

[build-dependencies]
lalrpop = "0.19.9"
